services:
  # ==========================================
  # PROJEKT 1: POETRY STREAM
  # ==========================================

  # ==========================================
  # PROJEKT 2: WORKDONE
  # ==========================================
  postgres-workdone:
    image: ankane/pgvector:latest
    ports:
      - "5432:5432"
    container_name: workdone-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: workdonesql
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    deploy:
      resources:
        limits:
          memory: 256M
    volumes:
      - /share/CACHEDEV1_DATA/Container/workdone/postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devuser -d workdonesql"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - shared-net

  kafka-workdone:
    image: apache/kafka:3.8.0
    container_name: workdone-kafka
    restart: unless-stopped
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-workdone:9092
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-workdone:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    deploy:
      resources:
        limits:
          memory: 768M
    networks:
      - shared-net

  backend-workdone:
    image: ghcr.io/widlakolak/workdone/backend:latest
    container_name: workdone
    restart: unless-stopped
    depends_on:
      postgres-workdone:
        condition: service_healthy
    environment:
      # AI API KEYS
      SPRING_AI_GOOGLE_GENAI_API_KEY: ${GEMINI_API_KEY}
      SPRING_AI_OPENAI_API_KEY: ${OPENAI_API_KEY}
      SPRING_AI_GROQ_API_KEY: ${GROQ_API_KEY}
      SPRING_AI_COHERE_API_KEY: ${COHERE_API_KEY}
      
      # DISCORD SECURITY
      DISCORD_PUBLIC_KEY: ${DISCORD_PUBLIC_KEY}

      # DATABASE
      DB_HOST: postgres-workdone
      DB_PORT: 5432
      DB_NAME: workdonesql
      DB_USERNAME: devuser
      DB_PASSWORD: devpassword
      
      # INFRA
      KAFKA_BOOTSTRAP_SERVERS: kafka-workdone:9092
    volumes:
      - /share/CACHEDEV1_DATA/Container/workdone/profile-input:/data/workdone/profile-input
    deploy:
      resources:
        limits:
          memory: 1G
    networks:
      - shared-net

  # ==========================================
  # WSPÓLNY CLOUDFLARE TUNNEL
  # ==========================================
  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: shared-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run --protocol http2
    environment:
      TUNNEL_TOKEN: ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - nginx
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge