spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/workdonesql
#    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:workdonesql}
    username: ${DB_USERNAME:devuser}
    password: ${DB_PASSWORD:devpassword}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY:}
        chat:
          options:
            model: gemini-2.5-flash-lite
    openai:
      api-key: ${OPENAI_API_KEY:}
    model:
      chat: google-genai
      embedding:
        enabled: true
        provider: openai
    vectorstore:
      pgvector:
        initialize-schema: true
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 768

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-workdone:9092}
    consumer:
      group-id: workdone-analyzer-group
      auto-offset-reset: earliest

workdone:
  profile:
    input-directory: /data/workdone/profile-input

  matching:
    ai-threshold-min: 50.0
    ai-threshold-max: 85.0
    instant-threshold: 90.0
    digest-threshold: 60.0
    archive-threshold: 40.0
    must-have-keywords:
      - java
      - spring boot
      - sql

  scheduling:
    ingestion-cron: "0 0 */2 * * *"
    digest-cron: "0 0 18 * * *"
    zone-id: Europe/Warsaw

  discord:
    instant:
      enabled: false
      url:
    digest:
      enabled: false
      url:

  providers:
    justjoinit:
      enabled: true
      base-url: https://api.justjoin.it
      offers-path: /v2/user-panel/offers
      priority: HIGH
      filters:
        keywords: [ java, spring ]
        allowed-cities: [ lodz ]
        allow-remote: true
        allow-hybrid: true

    nofluffjobs:
      enabled: true
      priority: HIGH
      filters:
        keywords: [ java, spring-boot ]
        experience-levels: [ junior, mid ]
        allow-remote: true
        allow-hybrid: true

    theprotocol:
      enabled: true
      priority: MEDIUM
      filters:
        allowed-cities: [ lodz ]
        work-modes: [ hybrid, remote ]

    upwork:
      enabled: true
      priority: EXPERIMENTAL
      filters:
        query: "java spring rest"
        min-budget-usd: 500
        remote-only: true