spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/workdone
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: workdone-analyzer-group
      auto-offset-reset: earliest